export type Language = 'en' | 'hi' | 'sa';

export const translations = {
  en: {
    // Navigation
    'nav.about': 'About Us',
    'nav.courses': 'Courses',
    'nav.calculators': 'Calculators',
    'nav.masterclass': 'Free Masterclass',
    'nav.webinars': 'Explore Webinars',
    'nav.login': 'Login',
    'nav.studentPortal': 'Student Portal',
    'nav.guruPortal': 'Guru Portal',
    'nav.adminPortal': 'Admin Portal',
    'nav.spiritualBasket': 'Spiritual Basket',
    'nav.myPath': 'My Spiritual Path',
    'nav.myLearning': 'My Sacred Learning',
    'nav.invite': 'Invite New Seekers',
    'nav.allCourses': 'All Courses',
    'nav.astrologyDropdown': 'Astrology & Jyotish',
    'nav.linguisticsDropdown': 'Linguistics & Chanting',

    // Hero
    'hero.title': 'SANATAN GURUKUL',
    'hero.subtitle': 'तमसो मा ज्योतिर्गमय',
    'hero.tagline': '"Lead me from darkness to spiritual light"',
    'hero.description': 'Connect with authentic Vedic lineages, master ancient scriptures, compute astrological charts, and study with advanced AI mentors.',
    'hero.explore': 'Explore Sacred Paths',
    'hero.trial': 'Start Free Trial',

    // Features
    'features.title': 'Sacred Vedic Gates',
    'features.subtitle': 'Enter the timeless streams of Vedic wisdom, astrological mathematics, and spiritual tools.',
    'features.astrologyTitle': 'Kundli Chart Generator',
    'features.astrologyDesc': 'Compute birth charts (D1, D9) using traditional Lahiri Sidereal Zodiac parameters.',
    'features.panchangTitle': 'Panchang & Muhurat',
    'features.panchangDesc': 'Discover auspicious timings (Shubha Muhurat), Rahu Kalam, and daily astronomical alignments.',
    'features.ramshalakaTitle': 'Ram Shalaka Prashnavali',
    'features.ramshalakaDesc': 'Seek divine direction from the Ramcharitmanas grid with instant Sanskrit exegesis.',
    'features.tarotTitle': 'Tarot Guidance Oracle',
    'features.tarotDesc': 'Draw sacred cards for career, relationships, and spiritual growth with Vedic insights.',
    'features.numerologyTitle': 'Numerology Calculator',
    'features.numerologyDesc': 'Calculate life path numbers, destiny numbers, and planetary vibrations.',
    'features.planetaryTitle': 'Planetary Positions',
    'features.planetaryDesc': 'Track real-time celestial movements and planetary coordinates.',

    // Portals & LMS
    'portal.streak': 'Streak',
    'portal.daysActive': 'Days Active',
    'portal.streakTitle': 'Guru Sadhana Streak',
    'portal.xp': 'Siddhi XP',
    'portal.welcome': 'Hari Om, Seeker',
    'portal.welcomeDesc': 'Welcome to your sacred space. Progress on your spiritual path and gain divine insights.',
    'portal.lockedCert': '🔒 Certificate Locked',
    'portal.lockedCertDesc': 'Achieve 100% video progress to unlock this certificate.',
    'portal.unlockedCert': '🏆 Certificate Unlocked!',
    'portal.unlockedCertDesc': 'Siddha congratulations! Your mastery has been verified by the lineage.',
    'portal.claimHonors': 'Claim Honors',
    'portal.lessons': 'Lessons',
    'portal.completeLesson': 'Complete Lesson',
    'portal.activeLecture': 'Active Lecture',
    'portal.timecode': 'TIMECODE',
    'portal.pause': 'PAUSE RECIPROCATION',
    'portal.resume': 'RESUME CHANTING',
    'portal.notesTitle': '✏️ Study Reflections & Shastras Notes',
    'portal.notesPlaceholder': 'Log insight resonance or technical parameters of this time frame...',
    'portal.commitNote': 'Commit Note in Registry',
    'portal.transcriptTitle': '📖 Sankalp Transcripts translation',
    'portal.pathTitle': 'Your Lineage Spiritual Path Progression',
    'portal.pathSubtitle': 'Every video, transcript reflection, custom summary, or quiz attempt pushes your status within the Sanatan Gurukul registry network.',

    // Calculators
    'calc.enterDetails': 'Enter Birth Parameters',
    'calc.calcBtn': 'Calculate Auspicious Alignment',
    'calc.sunRise': 'Sunrise',
    'calc.sunSet': 'Sunset',
    'calc.rahuKalam': 'Rahu Kalam',
    'calc.brahmaMuhurta': 'Brahma Muhurta',
    'calc.positive': 'Positive Verdict',
    'calc.caution': 'Caution Needed',
    'calc.negative': 'Negative Verdict',
    'calc.name': 'Your Name',
    'calc.question': 'State your query to the Oracle...',
    'calc.dob': 'Date of Birth',
    'calc.tob': 'Time of Birth',
    'calc.city': 'Birth City (e.g. Varanasi)',
    'calc.gender': 'Gender',
    'calc.submitQuestion': 'Transmit Query to Oracle'
  },
  hi: {
    // Navigation
    'nav.about': 'हमारे बारे में',
    'nav.courses': 'पाठ्यक्रम',
    'nav.calculators': 'कैलकुलेटर',
    'nav.masterclass': 'मुफ़्त मास्टरक्लास',
    'nav.webinars': 'वेबिनार खोजें',
    'nav.login': 'लॉग इन',
    'nav.studentPortal': 'छात्र पोर्टल',
    'nav.guruPortal': 'गुरु पोर्टल',
    'nav.adminPortal': 'एडमिन पोर्टल',
    'nav.spiritualBasket': 'आध्यात्मिक टोकरी',
    'nav.myPath': 'मेरा आध्यात्मिक मार्ग',
    'nav.myLearning': 'मेरा पवित्र शिक्षण',
    'nav.invite': 'नए साधकों को आमंत्रित करें',
    'nav.allCourses': 'सभी पाठ्यक्रम',
    'nav.astrologyDropdown': 'ज्योतिष और संबद्ध विज्ञान',
    'nav.linguisticsDropdown': 'भाषाविज्ञान और मंत्रोच्चार',

    // Hero
    'hero.title': 'सनातन गुरुकुल',
    'hero.subtitle': 'तमसो मा ज्योतिर्गमय',
    'hero.tagline': '"मुझे अंधकार से प्रकाश की ओर ले चलो"',
    'hero.description': 'प्रामाणिक वैदिक परंपराओं से जुड़ें, प्राचीन शास्त्रों में महारत हासिल करें, ज्योतिषीय गणना करें, और उन्नत एआई गुरुओं के साथ अध्ययन करें।',
    'hero.explore': 'पवित्र मार्ग का अन्वेषण करें',
    'hero.trial': 'मुफ़्त परीक्षण शुरू करें',

    // Features
    'features.title': 'पवित्र वैदिक द्वार',
    'features.subtitle': 'वैदिक ज्ञान, ज्योतिषीय गणित और आध्यात्मिक साधनाओं की कालजयी धाराओं में प्रवेश करें।',
    'features.astrologyTitle': 'कुंडली चार्ट निर्माता',
    'features.astrologyDesc': 'पारंपरिक लाहिड़ी नक्षत्र राशि मापदंडों का उपयोग करके जन्म कुंडली (D1, D9) की गणना करें।',
    'features.panchangTitle': 'पंचांग और मुहूर्त',
    'features.panchangDesc': 'शुभ मुहूर्त, राहु काल और दैनिक खगोलीय संरेखण की खोज करें।',
    'features.ramshalakaTitle': 'राम शलाका प्रश्नावली',
    'features.ramshalakaDesc': 'त्वरित संस्कृत व्याख्या के साथ रामचरितमानस ग्रिड से दिव्य मार्गदर्शन प्राप्त करें।',
    'features.tarotTitle': 'टैरो मार्गदर्शन ओरेकल',
    'features.tarotDesc': 'वैदिक अंतर्दृष्टि के साथ आजीविका, संबंधों और आध्यात्मिक विकास के लिए पवित्र कार्ड चुनें।',
    'features.numerologyTitle': 'अंकशास्त्र कैलकुलेटर',
    'features.numerologyDesc': 'जीवन पथ संख्या, भाग्य संख्या और ग्रहों के कंपन की गणना करें।',
    'features.planetaryTitle': 'ग्रहों की स्थिति',
    'features.planetaryDesc': 'वास्तविक समय में खगोलीय गतियों और ग्रहों के निर्देशांक को ट्रैक करें।',

    // Portals & LMS
    'portal.streak': 'निरंतरता',
    'portal.daysActive': 'दिन सक्रिय',
    'portal.streakTitle': 'गुरु साधना निरंतरता',
    'portal.xp': 'सिद्धि XP',
    'portal.welcome': 'हरि ओम, साधक',
    'portal.welcomeDesc': 'आपके पवित्र स्थान में आपका स्वागत है। अपने आध्यात्मिक मार्ग पर प्रगति करें और दिव्य अंतर्दृष्टि प्राप्त करें।',
    'portal.lockedCert': '🔒 प्रमाणपत्र लॉक है',
    'portal.lockedCertDesc': 'प्रमाणपत्र को अनलॉक करने के लिए 100% वीडियो प्रगति प्राप्त करें।',
    'portal.unlockedCert': '🏆 प्रमाणपत्र अनलॉक हो गया!',
    'portal.unlockedCertDesc': 'सिद्धि की बधाई! आपकी महारत को गुरुकुल परंपरा द्वारा सत्यापित किया गया है।',
    'portal.claimHonors': 'सम्मान प्राप्त करें',
    'portal.lessons': 'पाठ',
    'portal.completeLesson': 'पाठ पूर्ण करें',
    'portal.activeLecture': 'सक्रिय व्याख्यान',
    'portal.timecode': 'समय सूचक',
    'portal.pause': 'अध्ययन विराम',
    'portal.resume': 'अध्ययन जारी रखें',
    'portal.notesTitle': '✏️ अध्ययन चिंतन और शास्त्र नोट्स',
    'portal.notesPlaceholder': 'इस समय अवधि के दौरान अपने विचारों और गुरु के वचनों को सहेजें...',
    'portal.commitNote': 'नोट सहेजें',
    'portal.transcriptTitle': '📖 संकल्प प्रतिलिपि अनुवाद',
    'portal.pathTitle': 'आपकी गुरुकुल आध्यात्मिक मार्ग प्रगति',
    'portal.pathSubtitle': 'हर वीडियो, प्रतिलिपि चिंतन, या प्रश्नोत्तरी प्रयास आपको सनातन गुरुकुल की वंशावली में आगे बढ़ाता है।',

    // Calculators
    'calc.enterDetails': 'जन्म विवरण दर्ज करें',
    'calc.calcBtn': 'शुभ संरेखण की गणना करें',
    'calc.sunRise': 'सूर्योदय',
    'calc.sunSet': 'सूर्यास्त',
    'calc.rahuKalam': 'राहु काल',
    'calc.brahmaMuhurta': 'ब्रह्म मुहूर्त',
    'calc.positive': 'सकारात्मक संकेत',
    'calc.caution': 'सावधानी की आवश्यकता',
    'calc.negative': 'नकारात्मक संकेत',
    'calc.name': 'आपका नाम',
    'calc.question': 'ओरेकल से अपना प्रश्न पूछें...',
    'calc.dob': 'जन्म तिथि',
    'calc.tob': 'जन्म समय',
    'calc.city': 'जन्म शहर (उदा. वाराणसी)',
    'calc.gender': 'लिंग',
    'calc.submitQuestion': 'प्रश्न प्रेषित करें'
  },
  sa: {
    // Navigation
    'nav.about': 'अस्माकं विषये',
    'nav.courses': 'पाठ्यक्रमाः',
    'nav.calculators': 'गणकयन्त्राणि',
    'nav.masterclass': 'निःशुल्क-प्रबोधनम्',
    'nav.webinars': 'संगोष्ठी-अन्वेषणम्',
    'nav.login': 'प्रवेशः',
    'nav.studentPortal': 'छात्र-द्वारम्',
    'nav.guruPortal': 'गुरु-द्वारम्',
    'nav.adminPortal': 'प्रबन्धक-द्वारम्',
    'nav.spiritualBasket': 'आध्यात्मिक-पिटकम्',
    'nav.myPath': 'मम आध्यात्मिक-मार्गः',
    'nav.myLearning': 'मम पवित्र-शिक्षणम्',
    'nav.invite': 'नूतन-जिज्ञासु-आमन्त्रणम्',
    'nav.allCourses': 'सर्वे पाठ्यक्रमाः',
    'nav.astrologyDropdown': 'ज्योतिषशास्त्रम्',
    'nav.linguisticsDropdown': 'भाषाशास्त्रम् व्याकरणञ्च',

    // Hero
    'hero.title': 'सनातन-गुरुकुलम्',
    'hero.subtitle': 'तमसो मा ज्योतिर्गमय',
    'hero.tagline': '"तमसो मा ज्योतिर्गमय"',
    'hero.description': 'प्रामाणिक-वैदिक-परम्पराभिः सह सम्बद्धता, प्राचीनशास्त्राणां पाण्डित्यम्, ज्योतिषीयगणना, प्रगत-कृत्रिमबुद्धि-गुरुभिः सह अध्ययनञ्च।',
    'hero.explore': 'पवित्रमार्गस्य अन्वेषणम्',
    'hero.trial': 'निःशुल्क-परीक्षणारम्भः',

    // Features
    'features.title': 'पवित्राः वैदिक-द्वाराः',
    'features.subtitle': 'वैदिकज्ञानस्य, ज्योतिषीयगणितस्य, आध्यात्मिकसाधनानाञ्च अमृतधारासु प्रविशन्तु।',
    'features.astrologyTitle': 'कुण्डली-लेखनम्',
    'features.astrologyDesc': 'पारम्परिक-लाहिड़ी-नाक्षत्रराशि-मानदण्डैः जन्मपत्रिकायाः (D1, D9) सूक्ष्मगणना।',
    'features.panchangTitle': 'पञ्चाङ्ग-मुहूर्त्तौ',
    'features.panchangDesc': 'शुभमुहूर्त्तानां, राहुकालस्य, दैनिक-खगोलीय-ग्रहस्थितीनाञ्च सम्यक् ज्ञानम्।',
    'features.ramshalakaTitle': 'रामशलाका प्रश्नावली',
    'features.ramshalakaDesc': 'त्वरित-संस्कृत-व्याख्यया सह रामcharitमानस-कोष्ठकात् दिव्यमार्गदर्शनम्।',
    'features.tarotTitle': 'दैवी-टैरो-मार्गदर्शनम्',
    'features.tarotDesc': 'वैदिक-दृष्ट्या आजीविका-सम्बन्ध-आध्यात्मिकविकासानां कृते पवित्राणां पत्राणां चयनम्।',
    'features.numerologyTitle': 'अङ्कशास्त्र-गणकम्',
    'features.numerologyDesc': 'जीवनमार्ग-भाग्य-ग्रहीयस्पन्दनानाम् अङ्कशास्त्रेण सूक्ष्ममाकलनम्।',
    'features.planetaryTitle': 'ग्रहस्थिति-दर्पणम्',
    'features.planetaryDesc': 'वास्तविकसमये खगोलीयगतीनां ग्रहीयनिर्देशाङ्कानाञ्च निरीक्षणम्।',

    // Portals & LMS
    'portal.streak': 'सातत्यम्',
    'portal.daysActive': 'दिवसाः सक्रियाः',
    'portal.streakTitle': 'गुरु-साधना-सातत्यम्',
    'portal.xp': 'सिद्धि-बिन्दवः',
    'portal.welcome': 'हरिः ओम्, जिज्ञासो',
    'portal.welcomeDesc': 'मङ्गलमयं स्वागतम्। स्वकीय-आध्यात्मिकमार्गे वर्धध्वं दिव्यज्ञानं लभध्वञ्च।',
    'portal.lockedCert': '🔒 प्रमाणपत्रं कीलितम्',
    'portal.lockedCertDesc': 'प्रमाणपत्रस्य विमोचनाय शतप्रतिशतं प्रगतिं प्राप्नुत।',
    'portal.unlockedCert': '🏆 प्रमाणपत्रं मुक्तम्!',
    'portal.unlockedCertDesc': 'सिद्धिः प्राप्ता! भवतः नैपुण्यं गुरुकुलपरम्परया स्वीकृतम्।',
    'portal.claimHonors': 'सम्मानं गृह्यताम्',
    'portal.lessons': 'पाठाः',
    'portal.completeLesson': 'पाठ-समाप्तिः',
    'portal.activeLecture': 'सक्रिय-पाठः',
    'portal.timecode': 'समयखण्डः',
    'portal.pause': 'अध्ययन-विरामः',
    'portal.resume': 'अध्ययन-अनुवृत्तिः',
    'portal.notesTitle': '✏️ स्वाध्याय-चिन्तनम् शास्त्र-टिप्पणी च',
    'portal.notesPlaceholder': 'अस्मिन् समये उत्पन्नान् विचारान् गुरोः उपदेशांश्च लिखन्तु...',
    'portal.commitNote': 'टिप्पणीं सञ्चिनोतु',
    'portal.transcriptTitle': '📖 सङ्कल्प-भाष्य-प्रतिलिपिः',
    'portal.pathTitle': 'भवतः आध्यात्मिक-मार्ग-प्रगतिः',
    'portal.pathSubtitle': 'प्रत्येकं चलच्चित्रम्, स्वाध्याय-चिन्तनम्, परीक्षाप्रयासश्च भवन्तं सनातन-गुरुकुलस्य पञ्जिकायां श्रेष्ठपदं नयति।',

    // Calculators
    'calc.enterDetails': 'जन्म-विवरण-प्रविष्टिः',
    'calc.calcBtn': 'शुभ-संरेखणस्य गणना',
    'calc.sunRise': 'सूर्योदयः',
    'calc.sunSet': 'सूर्यास्तः',
    'calc.rahuKalam': 'राहुकालः',
    'calc.brahmaMuhurta': 'ब्रह्ममुहूर्त्तः',
    'calc.positive': 'अनुकूलः निर्णयः',
    'calc.caution': 'सावधानता अपेक्षितः',
    'calc.negative': 'प्रतिकूलः निर्णयः',
    'calc.name': 'भवतः नाम',
    'calc.question': 'दैवी-प्रश्नावल्यां स्वकीयं प्रश्नं लिखतु...',
    'calc.dob': 'जन्मतिथिः',
    'calc.tob': 'जन्मसमयः',
    'calc.city': 'जन्मस्थानम् (उदा. वाराणसी)',
    'calc.gender': 'लिङ्गम्',
    'calc.submitQuestion': 'प्रश्नं प्रेषयतु'
  }
};

export function t(key: keyof typeof translations['en'], lang: Language): string {
  const dict = translations[lang] || translations['en'];
  return dict[key] || translations['en'][key] || key;
}
